bind 127.0.0.1
port 6379

protected-mode yes

supervised systemd
daemonize no

# =====================
# MEMORY (важливо для кешу)
# =====================
maxmemory 1024mb
maxmemory-policy allkeys-lru

# =====================
# PERSISTENCE
# =====================
appendonly yes
appendfsync everysec

save 900 1
save 300 10
save 60 10000

# =====================
# PERFORMANCE
# =====================
tcp-keepalive 300
timeout 0
databases 16

hz 10
dynamic-hz yes

# =====================
# CLIENTS
# =====================
maxclients 10000

# =====================
# SECURITY (мінімальний хард)
# =====================
rename-command FLUSHALL ""
rename-command FLUSHDB ""

# =====================
# LOGGING
# =====================
loglevel notice
logfile /var/log/redis/redis-server.log

# =====================
# FILES
# =====================
dir /var/lib/redis
dbfilename dump.rdb
appendfilename "appendonly.aof"